official=zsh gnome-terminal fastfetch eza bat fzf zoxide ripgrep fd git tree jq less man-db man-pages ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols ttf-nerd-fonts-symbols-mono zsh-autosuggestions zsh-syntax-highlighting zsh-completions
aur=zsh-theme-powerlevel10k-git
